name: Android Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checkout the code

      # Set up Java
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"

      # Install dependencies
      - run: flutter pub get

      # Run tests (optional)
      # - run: flutter test

      # Build APK
      - run: flutter build apk --release

      # Upload APK as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
