name: Android Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checkout the code

      # Set up Java 21 explicitly (with proper env variables)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      # Verify Java installation (debugging)
      - name: Check Java installation
        run: |
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "which java: $(which java)"

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"

      # Fix Gradle Java Home (CRITICAL STEP)
      - name: Configure Gradle Java Home
        run: |
          echo "ORG_GRADLE_PROJECT_org.gradle.java.home=$JAVA_HOME" >> $GITHUB_ENV
          echo "Using Gradle Java Home: $JAVA_HOME"

      # Install dependencies
      - run: flutter pub get

      # Run tests (optional)
      # - run: flutter test

      # Build APK
      - run: flutter build apk --release

      # Upload APK as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
